Update action.yml

diff --git a/run-and-capture-error/action.yml b/run-and-capture-error/action.yml
--- a/run-and-capture-error/action.yml
+++ b/run-and-capture-error/action.yml
@@ -16,5 +16,15 @@ runs:
   steps:
     - run: |
         echo " ${{ inputs.command }} - ${{ inputs.error-log-path }} - ${{ inputs.step-name }} "
-        ${{ inputs.command }} > ${{ inputs.error-log-path }} 2>&1 || echo "Step failed: [${{ inputs.step-name }}]" >> ${{ inputs.error-log-path }}
+         ${{ inputs.command }} ?>> ${{ inputs.error-log-path }}
+#        ${{ inputs.command }} 2>> ${{ inputs.error-log-path }} || echo "Step failed: [${{ inputs.step-name }}]" >> ${{ inputs.error-log-path }}
+      shell: bash
+
+    - name: Display errorssss.txt contents
+      if: failure()
+      run: |
+        ls ${{ github.workspace }}
+        echo "Contents of errors.txt:"
+        cat ${{ inputs.error-log-path }}
+
       shell: bash
